name: Build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2025.10.0
    with:
      files: |
        esphome/generic-esp32s3.yaml
        esphome/esp32-s3-box3.yaml
      esphome-version: "2025.x"
